import {Inter} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import theme from './theme.js';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QwizzCards",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <ThemeProvider theme={theme}>
        <CssBaseline/>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>

      </ThemeProvider>

    </ClerkProvider>
  );
}
